from __future__ import annotations

from typing import Any

from modules.prompt_shortcuts.contracts import PromptShortcutProfileDescriptor

_COMMON_PALETTE: tuple[dict[str, Any], ...] = (
    {"id": "attention", "label": "( )", "operator": "ATTENTION", "kind": "wrap", "prefix": "(", "suffix": ")", "placeholder": "subject", "description": "Increase attention using parentheses.", "example": "(subject)"},
    {"id": "deemphasis", "label": "[ ]", "operator": "DEEMPHASIS", "kind": "wrap", "prefix": "[", "suffix": "]", "placeholder": "subject", "description": "Decrease attention using square brackets.", "example": "[subject]"},
    {"id": "weight", "label": ":1.2", "operator": "WEIGHT", "kind": "wrap", "prefix": "(", "suffix": ":1.2)", "placeholder": "subject", "description": "Apply a numeric attention weight.", "example": "(subject:1.2)"},
    {"id": "alternate", "label": "A|B", "operator": "ALTERNATE", "kind": "wrap", "prefix": "[", "suffix": "|option]", "placeholder": "subject", "description": "Alternate prompt text across sampling steps.", "example": "[subject|option]"},
    {"id": "schedule", "label": "A→B", "operator": "SCHEDULE", "kind": "wrap", "prefix": "[", "suffix": ":replacement:0.5]", "placeholder": "subject", "description": "Schedule a prompt transition.", "example": "[subject:replacement:0.5]"},
    {"id": "and", "operator": "AND", "kind": "insert", "insert": " AND ", "description": "Create a composable conditioning branch.", "example": "cat:1.2 AND dog:0.8"},
    {"id": "group", "label": "{ }", "operator": "GROUP_OPEN", "kind": "wrap", "prefix": "{", "suffix": "}", "placeholder": "items", "description": "Group prompt items.", "example": "{red, blue}"},
    {"id": "sequence", "operator": "SEQUENCE", "kind": "insert", "insert": "::", "description": "Insert a sequence separator.", "example": "owner::attribute::value!"},
    {"id": "deep-sequence", "operator": "DEEP_SEQUENCE", "kind": "insert", "insert": ":::", "description": "Insert a deep/top-level sequence separator.", "example": "owner:::attribute::value!!!"},
    {"id": "close", "operator": "CLOSE", "kind": "insert", "insert": "!!", "description": "Close the current sequence using this profile's shortcut.", "example": "!!"},
    {"id": "top-close", "operator": "TOP_CLOSE", "kind": "insert", "insert": "!!!", "description": "Close the top-level/deep sequence.", "example": "!!!"},
    {"id": "bind", "operator": "BIND", "kind": "template", "template": "{{selection}} BIND{subject => detail}", "placeholder": "base prompt", "description": "Bind details to a base prompt.", "example": "portrait BIND{girl => red eyes}", "parsers": ["parser21", "superhybrid"]},
    {"id": "chunk", "operator": "CHUNK", "kind": "template", "template": "CHUNK{ {{selection}} | option }", "placeholder": "subject", "description": "Create a Parser 21 chunk block.", "example": "CHUNK{wolf | moonlight}", "parsers": ["parser21", "superhybrid"]},
    {"id": "blend", "operator": "BLEND", "kind": "template", "template": "BLEND{ {{selection}} * 1.0 | option * 1.0 }", "placeholder": "subject", "description": "Blend weighted Parser 21 branches.", "example": "BLEND{wolf * 1.0 | moonlight * 0.6}", "parsers": ["parser21", "superhybrid"]},
    {"id": "pool", "operator": "POOL", "kind": "template", "template": "POOL{ {{selection}} | option }", "placeholder": "subject", "description": "Create a Parser 21 pool block.", "example": "POOL{red | green | blue}", "parsers": ["parser21", "superhybrid"]},
    {"id": "morph", "operator": "MORPH", "kind": "template", "template": "MORPH{ {{selection}} => target }", "placeholder": "subject", "description": "Create a Parser 21 morph operation.", "example": "MORPH{day => night}", "parsers": ["parser21", "superhybrid"]},
    {"id": "assemble", "operator": "ASSEMBLE", "kind": "template", "template": "ASSEMBLE{ base={{selection}}, detail=detail }", "placeholder": "subject", "description": "Create a Parser 21 assemble block.", "example": "ASSEMBLE{base=portrait, detail=red eyes}", "parsers": ["parser21", "superhybrid"]},
)


def _emitters() -> dict[str, dict[str, str]]:
    return {
        "legacy": {
            "AND": "AND",
            "GROUP_OPEN": "{",
            "GROUP_CLOSE": "}",
            "SEQUENCE": "::",
            "DEEP_SEQUENCE": "::",
            "CLOSE": "!",
            "TOP_CLOSE": "!!",
        },
        "combined": {
            "AND": "AND",
            "GROUP_OPEN": "{",
            "GROUP_CLOSE": "}",
            "SEQUENCE": "::",
            "DEEP_SEQUENCE": ":::",
            "CLOSE": "!!",
            "TOP_CLOSE": "!!!",
            "CHUNK": "CHUNK",
            "BLEND": "BLEND",
            "BIND": "BIND",
            "POOL": "POOL",
            "MORPH": "MORPH",
            "ASSEMBLE": "ASSEMBLE",
            "COMPOUND": "COMPOUND",
        },
        "parser21": {
            "AND": "AND",
            "GROUP_OPEN": "{",
            "GROUP_CLOSE": "}",
            "SEQUENCE": "::",
            "DEEP_SEQUENCE": ":::",
            "CLOSE": "!!",
            "TOP_CLOSE": "!!!",
            "CHUNK": "CHUNK",
            "BLEND": "BLEND",
            "BIND": "BIND",
            "POOL": "POOL",
            "MORPH": "MORPH",
            "ASSEMBLE": "ASSEMBLE",
            "COMPOUND": "COMPOUND",
        },
        "superhybrid": {
            "AND": "AND",
            "GROUP_OPEN": "{",
            "GROUP_CLOSE": "}",
            "SEQUENCE": "::",
            "DEEP_SEQUENCE": ":::",
            "CLOSE": "!!",
            "TOP_CLOSE": "!!!",
            "CHUNK": "CHUNK",
            "BLEND": "BLEND",
            "BIND": "BIND",
            "POOL": "POOL",
            "MORPH": "MORPH",
            "ASSEMBLE": "ASSEMBLE",
            "COMPOUND": "COMPOUND",
        },
    }


def builtin_prompt_shortcut_profiles() -> tuple[PromptShortcutProfileDescriptor, ...]:
    emitters = _emitters()
    return (
        PromptShortcutProfileDescriptor(
            profile_id="canonical",
            label="Canonical Operators",
            version="1",
            aliases={
                "AND": ("AND",),
                "GROUP_OPEN": ("{",),
                "GROUP_CLOSE": ("}",),
                "SEQUENCE": ("::",),
                "DEEP_SEQUENCE": (":::",),
                "CLOSE": ("!!",),
                "TOP_CLOSE": ("!!!",),
                "CHUNK": ("CHUNK",),
                "BLEND": ("BLEND",),
                "BIND": ("BIND",),
                "POOL": ("POOL",),
                "MORPH": ("MORPH",),
                "ASSEMBLE": ("ASSEMBLE",),
                "COMPOUND": ("COMPOUND",),
            },
            parser_emitters=emitters,
            compatible_parsers=("legacy", "parser21", "superhybrid", "combined"),
            description="Stable parser-independent operator names and symbols.",
            palette=_COMMON_PALETTE,
        ),
        PromptShortcutProfileDescriptor(
            profile_id="legacy_default",
            label="Legacy Default",
            version="1",
            aliases={
                "AND": ("AND",),
                "GROUP_OPEN": ("{",),
                "GROUP_CLOSE": ("}",),
                "SEQUENCE": ("::",),
                "CLOSE": ("!",),
                "TOP_CLOSE": ("!!",),
            },
            parser_emitters={"legacy": emitters["legacy"]},
            compatible_parsers=("legacy",),
            description="Preserves the existing IMAGE_GEN legacy prompt syntax.",
            palette=tuple(item for item in _COMMON_PALETTE if not item.get("parsers")),
        ),
        PromptShortcutProfileDescriptor(
            profile_id="advanced_symbols",
            label="Advanced Symbols",
            version="1",
            aliases={
                "AND": ("AND",),
                "GROUP_OPEN": ("{",),
                "GROUP_CLOSE": ("}",),
                "SEQUENCE": ("::",),
                "DEEP_SEQUENCE": (":::",),
                "CLOSE": ("!!",),
                "TOP_CLOSE": ("!!!",),
                "CHUNK": ("&&", "CHUNK"),
                "BLEND": ("<+>", "BLEND"),
                "BIND": ("BIND",),
                "POOL": ("$$", "POOL"),
                "MORPH": (">>", "MORPH"),
                "ASSEMBLE": ("@@", "ASSEMBLE"),
            },
            parser_emitters=emitters,
            compatible_parsers=("legacy", "parser21", "superhybrid", "combined"),
            description="IMAGE_GEN sequence symbols plus optional readable or symbolic Parser 21 operators.",
            palette=_COMMON_PALETTE,
        ),
        PromptShortcutProfileDescriptor(
            profile_id="parser21_native",
            label="Parser 21 Native",
            version="21",
            aliases={
                "AND": ("AND",),
                "GROUP_OPEN": ("{",),
                "GROUP_CLOSE": ("}",),
                "SEQUENCE": ("::",),
                "DEEP_SEQUENCE": (":::",),
                "CLOSE": ("!!",),
                "TOP_CLOSE": ("!!!",),
                "CHUNK": ("CHUNK",),
                "BLEND": ("BLEND",),
                "BIND": ("BIND",),
                "POOL": ("POOL",),
                "MORPH": ("MORPH",),
                "ASSEMBLE": ("ASSEMBLE",),
                "COMPOUND": ("COMPOUND",),
            },
            parser_emitters={"parser21": emitters["parser21"]},
            compatible_parsers=("parser21",),
            credit="Parser 21 syntax contributed by GitHub user Konpr",
            description="Native Prompt Parser 21 words and sequence symbols.",
            palette=_COMMON_PALETTE,
        ),
        PromptShortcutProfileDescriptor(
            profile_id="superhybrid_native",
            label="SuperHybrid PP21 Native",
            version="phase1-20260803",
            aliases={
                "AND": ("AND",),
                "GROUP_OPEN": ("{",),
                "GROUP_CLOSE": ("}",),
                "SEQUENCE": ("::",),
                "DEEP_SEQUENCE": (":::",),
                "CLOSE": ("!!",),
                "TOP_CLOSE": ("!!!",),
                "CHUNK": ("CHUNK",),
                "BLEND": ("BLEND",),
                "BIND": ("BIND",),
                "POOL": ("POOL",),
                "MORPH": ("MORPH",),
                "ASSEMBLE": ("ASSEMBLE",),
                "COMPOUND": ("COMPOUND",),
            },
            parser_emitters={"superhybrid": emitters["superhybrid"]},
            compatible_parsers=("superhybrid",),
            credit="SuperHybrid update based on Prompt Parser 21",
            description="Native SuperHybrid PP21 syntax with Phase 1 CFG Lab bridging.",
            palette=_COMMON_PALETTE,
        ),
    )


BUILTIN_PARSER_PRESETS: tuple[dict[str, Any], ...] = (
    {
        "preset_id": "legacy_default",
        "name": "Legacy Default",
        "prompt_parser_name": "legacy",
        "shortcut_profile_name": "legacy_default",
        "prompt_parser_kwargs": {},
        "fallback_policy": "fail",
        "hires_inheritance": "same_as_base",
        "builtin": True,
    },
    {
        "preset_id": "advanced_symbols_legacy",
        "name": "Advanced Symbols — Legacy",
        "prompt_parser_name": "legacy",
        "shortcut_profile_name": "advanced_symbols",
        "prompt_parser_kwargs": {},
        "fallback_policy": "fail",
        "hires_inheritance": "same_as_base",
        "builtin": True,
    },
    {
        "preset_id": "parser21_native",
        "name": "Parser 21 Native",
        "prompt_parser_name": "parser21",
        "shortcut_profile_name": "parser21_native",
        "prompt_parser_kwargs": {"use_visitor": True},
        "fallback_policy": "fail",
        "hires_inheritance": "same_as_base",
        "builtin": True,
    },
    {
        "preset_id": "parser21_advanced_symbols",
        "name": "Parser 21 with Advanced Symbols",
        "prompt_parser_name": "parser21",
        "shortcut_profile_name": "advanced_symbols",
        "prompt_parser_kwargs": {"use_visitor": True},
        "fallback_policy": "fail",
        "hires_inheritance": "same_as_base",
        "builtin": True,
    },
    {
        "preset_id": "superhybrid_native",
        "name": "SuperHybrid PP21 — Experimental",
        "prompt_parser_name": "superhybrid",
        "shortcut_profile_name": "superhybrid_native",
        "prompt_parser_kwargs": {
            "use_visitor": True,
            "prompt_cfg_behavior": "replace_ui",
        },
        "fallback_policy": "fail",
        "hires_inheritance": "same_as_base",
        "builtin": True,
    },
    {
        "preset_id": "combined_prefer_legacy",
        "name": "Combined Dispatch — Prefer Legacy",
        "prompt_parser_name": "combined",
        "shortcut_profile_name": "canonical",
        "prompt_parser_kwargs": {
            "strategy": "prefer_legacy",
            "preferred_parser": "legacy",
            "fail_on_ambiguous_route": False,
            "fallback_policy": "fail",
            "parser21_use_visitor": True,
            "parser21_use_old_scheduling": False,
        },
        "fallback_policy": "fail",
        "hires_inheritance": "same_as_base",
        "builtin": True,
    },
    {
        "preset_id": "combined_prefer_parser21",
        "name": "Combined Dispatch — Prefer Parser 21",
        "prompt_parser_name": "combined",
        "shortcut_profile_name": "canonical",
        "prompt_parser_kwargs": {
            "strategy": "prefer_parser21",
            "preferred_parser": "parser21",
            "fail_on_ambiguous_route": False,
            "fallback_policy": "fail",
            "parser21_use_visitor": True,
            "parser21_use_old_scheduling": False,
        },
        "fallback_policy": "fail",
        "hires_inheritance": "same_as_base",
        "builtin": True,
    },
    {
        "preset_id": "combined_strict",
        "name": "Combined Dispatch — Strict",
        "prompt_parser_name": "combined",
        "shortcut_profile_name": "canonical",
        "prompt_parser_kwargs": {
            "strategy": "strict_by_capability",
            "preferred_parser": "legacy",
            "fail_on_ambiguous_route": True,
            "fallback_policy": "fail",
            "parser21_use_visitor": True,
            "parser21_use_old_scheduling": False,
        },
        "fallback_policy": "fail",
        "hires_inheritance": "same_as_base",
        "builtin": True,
    },
)
