"""Canonical generation contracts used by every IMAGE_GEN system."""

from image_gen.contracts.compatibility import (
    SamplerCapabilities,
    SchedulerCompatibilityResult,
)
from image_gen.contracts.hires_diagnostics import (
    HIRES_CORRECTION_FINGERPRINT_VERSION,
    HIRES_FAILURE_STAGE_CODES,
    HIRES_FAILURE_STAGE_LABELS,
    build_hires_correction_audit,
    build_hires_correction_fingerprint,
    extract_hires_failure_stage,
    format_hires_failure,
    hires_failure_stage_label,
)
from image_gen.contracts.latent_vae import LatentVAEContract, resolve_latent_vae_contract
from image_gen.contracts.model_conditioning import (
    BranchModelConditioningKwargs,
    ModelConditioningKwargs,
    select_model_conditioning_branch,
)
from image_gen.contracts.protocols import (
    AdapterConformanceError,
    AdapterConformanceResult,
    DenoisedModelFnProtocol,
    GuidedModelFnProtocol,
    PromptAdapterProtocol,
    RawModelFnProtocol,
    SamplerAdapterProtocol,
    SchedulerAdapterProtocol,
    check_adapter_conformance,
    require_adapter_conformance,
)
from image_gen.contracts.runtime import (
    ConditioningOutput,
    GenerationRequest,
    PROMPT_ASSET_CONTRACT_VERSION,
    PromptAssetSelection,
    canonical_prompt_asset_source,
    canonical_prompt_asset_type,
    normalize_prompt_asset_list,
    GenerationResult,
    PipelineComponents,
    SamplerOutput,
    SchedulerOutput,
)

__all__ = [
    "AdapterConformanceError",
    "AdapterConformanceResult",
    "ConditioningOutput",
    "BranchModelConditioningKwargs",
    "ModelConditioningKwargs",
    "LatentVAEContract",
    "GenerationRequest",
    "GenerationResult",
    "HIRES_CORRECTION_FINGERPRINT_VERSION",
    "HIRES_FAILURE_STAGE_CODES",
    "HIRES_FAILURE_STAGE_LABELS",
    "build_hires_correction_audit",
    "build_hires_correction_fingerprint",
    "extract_hires_failure_stage",
    "format_hires_failure",
    "hires_failure_stage_label",
    "PROMPT_ASSET_CONTRACT_VERSION",
    "PromptAssetSelection",
    "canonical_prompt_asset_source",
    "canonical_prompt_asset_type",
    "normalize_prompt_asset_list",
    "DenoisedModelFnProtocol",
    "GuidedModelFnProtocol",
    "PipelineComponents",
    "PromptAdapterProtocol",
    "RawModelFnProtocol",
    "SamplerAdapterProtocol",
    "SamplerCapabilities",
    "SamplerOutput",
    "SchedulerAdapterProtocol",
    "SchedulerCompatibilityResult",
    "SchedulerOutput",
    "check_adapter_conformance",
    "select_model_conditioning_branch",
    "require_adapter_conformance",
    "resolve_latent_vae_contract",
]
